package utils.constClasses;

/*Generated by MPS */


public class ActionKey extends Key {
  private String name;

  public ActionKey(String name) {
    this.name = name;
  }

  public String getName() {
    return name;
  }

  public boolean isRightExpression(String key) {
    return key.equals(name);
  }

}
