package utils.constClasses;

/*Generated by MPS */


public class AndKeyExpression extends BinaryKeyExpression {
  public AndKeyExpression(KeyExpression leftOpernad, KeyExpression rightOperand) {
    super(leftOpernad, rightOperand);
  }
  public boolean isKeyInExpression(String key) {
    return leftOperand.isKeyInExpression(key) && rightOperand.isKeyInExpression(key);
  }

}
