package utils.constClasses;

/*Generated by MPS */


public class AndKeyExpression extends BinaryKeyExpression {
  public AndKeyExpression(KeyExpression leftOpernad, KeyExpression rightOperand) {
    super(leftOpernad, rightOperand);
  }
  public boolean isRightExpression(String key) {
    return leftOperand.isRightExpression(key) && rightOperand.isRightExpression(key);
  }

}
