package utils.constClasses;

/*Generated by MPS */


public abstract class BinaryKeyExpression extends KeyExpression {
  protected KeyExpression leftOperand;
  protected KeyExpression rightOperand;

  public BinaryKeyExpression(KeyExpression leftOperand, KeyExpression rightOperand) {
    this.leftOperand = leftOperand;
    this.rightOperand = rightOperand;
  }
}
