package utils.constClasses;

/*Generated by MPS */


public class ChatNode {
  protected String name;
  protected String text;

  public ChatNode(String name, String text) {
    this.name = name;
    this.text = text;
  }

  public String getText() {
    return text;
  }

  public String getName() {
    return name;
  }

  public boolean equals(Object other) {
    if (other == null) {
      return false;
    }
    if (other.getClass() != this.getClass()) {
      return false;
    }

    ChatNode otherChatNode = as_cf345p_a0a3a9(other, ChatNode.class);

    if (name == null) {
      return otherChatNode.getName() == null;
    }
    return name.equals(otherChatNode.getName());
  }

  public int hashCode() {
    if (name == null) {
      return 43;
    }
    return 43 + name.hashCode();
  }
  private static <T> T as_cf345p_a0a3a9(Object o, Class<T> type) {
    return (type.isInstance(o) ? (T) o : null);
  }
}
