package utils.constClasses;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.ArrayList;

public abstract class ChatBot {
  protected ContinuingChatNode startChatNode;
  protected List<ContinuingChatNode> middleChatNodes;
  protected List<ChatNode> endChatNodes;
  protected ChatNode currentChatNode;

  public ChatBot() {
    middleChatNodes = ListSequence.fromList(new ArrayList<ContinuingChatNode>());
    endChatNodes = ListSequence.fromList(new ArrayList<ChatNode>());
  }

  public String getCurrentText() {
    if (currentChatNode != null) {
      return currentChatNode.getText();
    } else {
      return "";
    }
  }

  public void continueChat(String key) {
    if (currentChatNode != null && !(ListSequence.fromList(endChatNodes).contains(currentChatNode))) {
      ChatNode newCurrentChatNode = null;
      final String newCurrentChatNodeName = as_jvk907_a0a0b0a0j(currentChatNode, ContinuingChatNode.class).findNextChatNode(key);
      if (startChatNode != null && startChatNode.getName().equals(newCurrentChatNodeName)) {
        newCurrentChatNode = startChatNode;
      } else if (ListSequence.fromList(middleChatNodes).count() >= 1) {
        newCurrentChatNode = ListSequence.fromList(middleChatNodes).findFirst((it) -> it.name.equals(newCurrentChatNodeName));
      }

      if (newCurrentChatNode == null && ListSequence.fromList(endChatNodes).count() >= 1) {
        newCurrentChatNode = ListSequence.fromList(endChatNodes).findFirst((it) -> it.name.equals(newCurrentChatNodeName));
      }

      if (newCurrentChatNode != null) {
        currentChatNode = newCurrentChatNode;
      }

    }
  }

  protected void setStartChatNode(ContinuingChatNode chatNode) {
    this.startChatNode = chatNode;
    this.currentChatNode = chatNode;
  }

  public boolean isFinished() {
    return ListSequence.fromList(this.endChatNodes).contains(this.currentChatNode);
  }

  private static <T> T as_jvk907_a0a0b0a0j(Object o, Class<T> type) {
    return (type.isInstance(o) ? (T) o : null);
  }
}
