package utils.constClasses;

/*Generated by MPS */


public class Connection {
  private Key key;
  private String chatNodeName;

  public Connection(Key key, String chatNodeName) {
    this.key = key;
    this.chatNodeName = chatNodeName;
  }

  public String getChatNode() {
    return this.chatNodeName;
  }

  public boolean isRightExpression(String key) {
    return this.key.isRightExpression(key);
  }

  public boolean isActionKeyConnection() {
    return key instanceof ActionKey;
  }

  public ActionKey getActionKey() {
    if (isActionKeyConnection()) {
      return as_a2izcv_a0a0a0l(key, ActionKey.class);
    } else {
      return null;
    }
  }
  private static <T> T as_a2izcv_a0a0a0l(Object o, Class<T> type) {
    return (type.isInstance(o) ? (T) o : null);
  }
}
