package utils.constClasses;

/*Generated by MPS */


public class Connection {
  private KeyExpression key;
  private String chatNodeName;

  public Connection(KeyExpression key, String chatNodeName) {
    this.key = key;
    this.chatNodeName = chatNodeName;
  }

  public String getChatNode() {
    return this.chatNodeName;
  }

  public boolean isKeyInExpression(String key) {
    return this.key.isKeyInExpression(key);
  }
}
