package utils.constClasses;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class ContinuingChatNode extends ChatNode {
  private List<Connection> connections;
  public ContinuingChatNode(String name, String text, List<Connection> connections) {
    super(name, text);
    this.connections = connections;
  }

  public String findNextChatNode(String key) {
    for (Connection connection : ListSequence.fromList(connections)) {
      if (connection.isKeyInExpression(key)) {
        return connection.getChatNode();
      }
    }

    return null;
  }
}
