package utils.constClasses;

/*Generated by MPS */


public class NotKeyExpression extends KeyExpression {
  private KeyExpression operand;

  public NotKeyExpression(KeyExpression operand) {
    this.operand = operand;
  }
  public boolean isKeyInExpression(String key) {
    return !(operand.isKeyInExpression(key));
  }

}
