package utils.constClasses;

/*Generated by MPS */


public class OrKeyExpression extends BinaryKeyExpression {
  public OrKeyExpression(KeyExpression leftOpernad, KeyExpression rightOperand) {
    super(leftOpernad, rightOperand);
  }
  public boolean isKeyInExpression(String key) {
    return leftOperand.isKeyInExpression(key) || rightOperand.isKeyInExpression(key);
  }

}
