package utils.constClasses;

/*Generated by MPS */


public class SimpleKeyExpression extends KeyExpression {
  private String key;
  public SimpleKeyExpression(String key) {
    this.key = key;
  }
  public boolean isRightExpression(String key) {
    return key.toLowerCase().contains(this.key.toLowerCase());
  }
}
