package utils.constClasses;

/*Generated by MPS */


public class VariableChatNode extends ChatNode {
  private String chatNodeName;
  private String value;

  public VariableChatNode(String name, String text, String variableName, String chatNodeName) {
    super(name, text, variableName);
    this.chatNodeName = chatNodeName;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public String processInput(String input) {
    this.value = input;
    return chatNodeName;
  }
  public String getVariableName() {
    return variableName;
  }

  public String getChatNodeName() {
    return chatNodeName;
  }
  public String getValue() {
    return value;
  }

}
