package utils.constClasses;

/*Generated by MPS */


public class VariableChatNode extends ChatNode {
  private String chatNodeName;
  private String value;
  private String ownVariableName;

  public VariableChatNode(String name, String text, String ownVariableName, String chatNodeName, String variableName) {
    super(name, text, variableName);
    this.ownVariableName = ownVariableName;

    this.chatNodeName = chatNodeName;
  }


  public void setValue(String value) {
    this.value = value;
  }

  public String processInput(String input) {
    this.value = input;
    return chatNodeName;
  }
  public String getOwnVariableName() {
    return ownVariableName;
  }

  public String getChatNodeName() {
    return chatNodeName;
  }
  public String getValue() {
    return value;
  }

}
